### ISSUE TITLE
Tables don't get exported if source is from FMP18

### ISSUE THREAD

**Issue by karstenw** [bc-m/fm-xml-export-exploder#3]
With the current fm-xml-export-exploder 0.1.1.

Result with fmp18 source:
![screen 2024-03-03 at 23 26 27](https://github.com/bc-m/fm-xml-export-exploder/assets/652583/b8342bf3-e391-411c-b78c-30dc130d56e5)

This file "- ID.xml" contains the FieldCatalog of the last table created.

Result with fmp19 source:
![screen 2024-03-03 at 23 26 53](https://github.com/bc-m/fm-xml-export-exploder/assets/652583/46ccbaa2-7adf-448c-965d-5eb8d2af46e7)

**Comment by bc-m** [comment]
Thank for creating an issue! I released [v0.1.2](https://github.com/bc-m/fm-xml-export-exploder/releases/tag/v0.1.2) with a fix.
